### ISSUE TITLE
按照进度发布编译出的 PDF 文件

### ISSUE THREAD

**Issue by iydon** [re-book/ptmst#2]
参照 `main.tex`
```
% !TeX program = latexmk
% !TeX options = -pdfxe -synctex=1 -interaction=nonstopmode -silent %DOCFILE%
```
编译仍然会产生以下问题，
```
! LaTeX Error: Command `\ulcorner' already defined.
! LaTeX Error: Command `\urcorner' already defined.
! LaTeX Error: Command `\llcorner' already defined.
! LaTeX Error: Command `\lrcorner' already defined.
! LaTeX Error: Command `\Bbbk' already defined.
```
使用环境为 `TeX Live 2019`，且在今天（2020年1月1日）使用 `tlmgr update --self --all` 更新，怀疑为宏包的版本问题，如果有可能希望根据进度上传 [release](https://github.com/re-book/ptmst/releases)。

PS：注意到不同的章节与 `main.tex` 放在相同目录下，是否可以考虑新建一个类似 `chapters` 的目录将不同章节文件放置在一起 :smile:

**Comment by kexplorning** [comment]
这是个奇怪的 bug（根据 ElegantLaTeX/ElegantBook/issues/59）。因为 `elegantbook.cls` 使用的是旧版的。

如果要过编译，先用最新的 `elegantbook.cls` 替换已有的；如果有提示 `newtxmath` 字体没有 `\leqslant` 那么在 `elegantbook.cls` 中把 `newtxmath` 字体禁用。

然后就是有些图片缺失，手动注释每一个缺失图片。

这样就可以过编译了。

---

编译以后看了看，发现还有好多内容没有完成啊。。

**Comment by OsbertWang** [comment]
2021年3月，向老师完成了整本书的工作，不日将上传源码。
