### ISSUE TITLE
How to build the pdf file from the source?

### ISSUE THREAD

**Issue by lavender-lee** [re-book/ptmst#4]
Hi, today I download the project to my desktop and then compile it in **TexMaker** editor with `XeLaTeX` (**TeXLive 2020**). However, I notice that there are so many errors and warnings occur. Here is a screeshot:

![image](https://user-images.githubusercontent.com/35004095/111807942-74f9af80-890e-11eb-937d-975d6d50a572.png)

**missfont.log**

           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZKai-Z03/OT
           mktextfm FZKai-Z03/B/OT
           mktextfm FZHei-B01/OT
           mktextfm FZHei-B01/I/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/BI/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZHei-B01/OT
           mktextfm FZHei-B01/OT
           mktextfm FZKai-Z03/OT
           mktextfm FZKai-Z03/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZKai-Z03/OT
           mktextfm FZShuSong-Z01/OT
           mktextfm FZShuSong-Z01/OT

So I would like to know how to address this problem. Thanks a bunch. I think this is a good example for me to learn TeX.

**Comment by CamuseCao** [comment]
As you can see, your system lacks a lot of fonts. You need to download `汉仪大宋简字体` . Check it in the end of `README.md` file, and you wil know where to download. Don't forget to install them.
