### ISSUE TITLE
可以更新一版Latex编译文档吗？

### ISSUE THREAD

**Issue by Whisht** [re-book/ptmst#6]
我发现了一些错误，想重新编译一下进行勘误，但是使用 overleaf 无法编译该项目。可以提供一下 latex 编译环境吗？谢谢

**Comment by RunshengHou** [comment]
您好！您的问题解决了吗，可不可以发我一份勘误后的版本？

**Comment by Whisht** [comment]
没有解决，目前还是无法编译

**Comment by yuxtech** [comment]
要编译这个文档，需要自己会处理一些字体问题，缺乏某种字体的话，需要讲对应的字体设置注释掉
