### ISSUE TITLE
公式错误

### ISSUE THREAD

**Issue by chaofanqw** [re-book/ptmst#9]
你好，第15页分配律公式1.1.4 应为(A∪B)∩C=(A∩C)∪(B∩C)

原书为：
![image](https://github.com/re-book/ptmst/assets/44720017/100821be-09b6-4830-9ca4-55b000881d22)

pdf为：
![image](https://github.com/re-book/ptmst/assets/44720017/d7f1e1a7-3ea2-4052-8bcc-a93ee05f174d)

**Comment by OsbertWang** [comment]
已经修订了问题，感谢。
